#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HybridAndroid.Resource", IsApplication=true)]

namespace HybridAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.LocalNotifications.Resource.Drawable.plugin_lc_smallicon = global::HybridAndroid.Resource.Drawable.plugin_lc_smallicon;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::HybridAndroid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::HybridAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0500a2
			public const int PageBackground = 2131034274;
			
			// aapt resource value: 0x7f0500a3
			public const int TitleBackground = 2131034275;
			
			// aapt resource value: 0x7f05000b
			public const int albumback = 2131034123;
			
			// aapt resource value: 0x7f05003b
			public const int aliceblue = 2131034171;
			
			// aapt resource value: 0x7f050031
			public const int antiquewhite = 2131034161;
			
			// aapt resource value: 0x7f050091
			public const int aqua = 2131034257;
			
			// aapt resource value: 0x7f050072
			public const int aquamarine = 2131034226;
			
			// aapt resource value: 0x7f050039
			public const int azure = 2131034169;
			
			// aapt resource value: 0x7f050007
			public const int background = 2131034119;
			
			// aapt resource value: 0x7f050036
			public const int beige = 2131034166;
			
			// aapt resource value: 0x7f05001c
			public const int bisque = 2131034140;
			
			// aapt resource value: 0x7f05000e
			public const int black = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int blanchedalmond = 2131034138;
			
			// aapt resource value: 0x7f05009c
			public const int blue = 2131034268;
			
			// aapt resource value: 0x7f05006a
			public const int blueviolet = 2131034218;
			
			// aapt resource value: 0x7f050001
			public const int bottom_item_line_color = 2131034113;
			
			// aapt resource value: 0x7f05005f
			public const int brown = 2131034207;
			
			// aapt resource value: 0x7f050043
			public const int burlywood = 2131034179;
			
			// aapt resource value: 0x7f0500a5
			public const int c1 = 2131034277;
			
			// aapt resource value: 0x7f0500a7
			public const int c10 = 2131034279;
			
			// aapt resource value: 0x7f0500a6
			public const int c4 = 2131034278;
			
			// aapt resource value: 0x7f050080
			public const int cadetblue = 2131034240;
			
			// aapt resource value: 0x7f050073
			public const int chartreuse = 2131034227;
			
			// aapt resource value: 0x7f05004e
			public const int chocolate = 2131034190;
			
			// aapt resource value: 0x7f050026
			public const int coral = 2131034150;
			
			// aapt resource value: 0x7f05007f
			public const int cornflowerblue = 2131034239;
			
			// aapt resource value: 0x7f050016
			public const int cornsilk = 2131034134;
			
			// aapt resource value: 0x7f050046
			public const int crimson = 2131034182;
			
			// aapt resource value: 0x7f050092
			public const int cyan = 2131034258;
			
			// aapt resource value: 0x7f05009e
			public const int darkblue = 2131034270;
			
			// aapt resource value: 0x7f050098
			public const int darkcyan = 2131034264;
			
			// aapt resource value: 0x7f050056
			public const int darkgoldenrod = 2131034198;
			
			// aapt resource value: 0x7f05005d
			public const int darkgray = 2131034205;
			
			// aapt resource value: 0x7f05009b
			public const int darkgreen = 2131034267;
			
			// aapt resource value: 0x7f05005e
			public const int darkgrey = 2131034206;
			
			// aapt resource value: 0x7f050053
			public const int darkkhaki = 2131034195;
			
			// aapt resource value: 0x7f050068
			public const int darkmagenta = 2131034216;
			
			// aapt resource value: 0x7f050081
			public const int darkolivegreen = 2131034241;
			
			// aapt resource value: 0x7f050025
			public const int darkorange = 2131034149;
			
			// aapt resource value: 0x7f050061
			public const int darkorchid = 2131034209;
			
			// aapt resource value: 0x7f050069
			public const int darkred = 2131034217;
			
			// aapt resource value: 0x7f050040
			public const int darksalmon = 2131034176;
			
			// aapt resource value: 0x7f050066
			public const int darkseagreen = 2131034214;
			
			// aapt resource value: 0x7f050084
			public const int darkslateblue = 2131034244;
			
			// aapt resource value: 0x7f05008a
			public const int darkslategray = 2131034250;
			
			// aapt resource value: 0x7f05008b
			public const int darkslategrey = 2131034251;
			
			// aapt resource value: 0x7f050096
			public const int darkturquoise = 2131034262;
			
			// aapt resource value: 0x7f050063
			public const int darkviolet = 2131034211;
			
			// aapt resource value: 0x7f05002a
			public const int deeppink = 2131034154;
			
			// aapt resource value: 0x7f050097
			public const int deepskyblue = 2131034263;
			
			// aapt resource value: 0x7f05007c
			public const int dimgray = 2131034236;
			
			// aapt resource value: 0x7f05007d
			public const int dimgrey = 2131034237;
			
			// aapt resource value: 0x7f05008f
			public const int dodgerblue = 2131034255;
			
			// aapt resource value: 0x7f050006
			public const int edt_font_value__color = 2131034118;
			
			// aapt resource value: 0x7f050057
			public const int firebrick = 2131034199;
			
			// aapt resource value: 0x7f050014
			public const int floralwhite = 2131034132;
			
			// aapt resource value: 0x7f050004
			public const int font_main_color = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int font_value_main_color = 2131034117;
			
			// aapt resource value: 0x7f05008d
			public const int forestgreen = 2131034253;
			
			// aapt resource value: 0x7f05002b
			public const int fuchsia = 2131034155;
			
			// aapt resource value: 0x7f050045
			public const int gainsboro = 2131034181;
			
			// aapt resource value: 0x7f050033
			public const int ghostwhite = 2131034163;
			
			// aapt resource value: 0x7f050020
			public const int gold = 2131034144;
			
			// aapt resource value: 0x7f050048
			public const int goldenrod = 2131034184;
			
			// aapt resource value: 0x7f05006d
			public const int gray = 2131034221;
			
			// aapt resource value: 0x7f05009a
			public const int green = 2131034266;
			
			// aapt resource value: 0x7f05005b
			public const int greenyellow = 2131034203;
			
			// aapt resource value: 0x7f05006e
			public const int grey = 2131034222;
			
			// aapt resource value: 0x7f05003a
			public const int honeydew = 2131034170;
			
			// aapt resource value: 0x7f050027
			public const int hotpink = 2131034151;
			
			// aapt resource value: 0x7f050050
			public const int indianred = 2131034192;
			
			// aapt resource value: 0x7f050082
			public const int indigo = 2131034242;
			
			// aapt resource value: 0x7f050010
			public const int ivory = 2131034128;
			
			// aapt resource value: 0x7f05003c
			public const int khaki = 2131034172;
			
			// aapt resource value: 0x7f050041
			public const int lavender = 2131034177;
			
			// aapt resource value: 0x7f050018
			public const int lavenderblush = 2131034136;
			
			// aapt resource value: 0x7f050074
			public const int lawngreen = 2131034228;
			
			// aapt resource value: 0x7f050015
			public const int lemonchiffon = 2131034133;
			
			// aapt resource value: 0x7f05005c
			public const int lightblue = 2131034204;
			
			// aapt resource value: 0x7f05003d
			public const int lightcoral = 2131034173;
			
			// aapt resource value: 0x7f050042
			public const int lightcyan = 2131034178;
			
			// aapt resource value: 0x7f05002f
			public const int lightgoldenrodyellow = 2131034159;
			
			// aapt resource value: 0x7f05004b
			public const int lightgray = 2131034187;
			
			// aapt resource value: 0x7f050065
			public const int lightgreen = 2131034213;
			
			// aapt resource value: 0x7f05004c
			public const int lightgrey = 2131034188;
			
			// aapt resource value: 0x7f050022
			public const int lightpink = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int lightsalmon = 2131034148;
			
			// aapt resource value: 0x7f05008e
			public const int lightseagreen = 2131034254;
			
			// aapt resource value: 0x7f05006b
			public const int lightskyblue = 2131034219;
			
			// aapt resource value: 0x7f050076
			public const int lightslategray = 2131034230;
			
			// aapt resource value: 0x7f050077
			public const int lightslategrey = 2131034231;
			
			// aapt resource value: 0x7f050059
			public const int lightsteelblue = 2131034201;
			
			// aapt resource value: 0x7f050011
			public const int lightyellow = 2131034129;
			
			// aapt resource value: 0x7f050094
			public const int lime = 2131034260;
			
			// aapt resource value: 0x7f050089
			public const int limegreen = 2131034249;
			
			// aapt resource value: 0x7f050030
			public const int linen = 2131034160;
			
			// aapt resource value: 0x7f05002c
			public const int magenta = 2131034156;
			
			// aapt resource value: 0x7f050071
			public const int maroon = 2131034225;
			
			// aapt resource value: 0x7f05007e
			public const int mediumaquamarine = 2131034238;
			
			// aapt resource value: 0x7f05009d
			public const int mediumblue = 2131034269;
			
			// aapt resource value: 0x7f050055
			public const int mediumorchid = 2131034197;
			
			// aapt resource value: 0x7f050064
			public const int mediumpurple = 2131034212;
			
			// aapt resource value: 0x7f050088
			public const int mediumseagreen = 2131034248;
			
			// aapt resource value: 0x7f050075
			public const int mediumslateblue = 2131034229;
			
			// aapt resource value: 0x7f050095
			public const int mediumspringgreen = 2131034261;
			
			// aapt resource value: 0x7f050083
			public const int mediumturquoise = 2131034243;
			
			// aapt resource value: 0x7f050051
			public const int mediumvioletred = 2131034193;
			
			// aapt resource value: 0x7f050090
			public const int midnightblue = 2131034256;
			
			// aapt resource value: 0x7f050034
			public const int mintcream = 2131034164;
			
			// aapt resource value: 0x7f05001b
			public const int mistyrose = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int moccasin = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int navajowhite = 2131034142;
			
			// aapt resource value: 0x7f050008
			public const int navigation_color = 2131034120;
			
			// aapt resource value: 0x7f05009f
			public const int navy = 2131034271;
			
			// aapt resource value: 0x7f050009
			public const int none_color = 2131034121;
			
			// aapt resource value: 0x7f05002e
			public const int oldlace = 2131034158;
			
			// aapt resource value: 0x7f05006f
			public const int olive = 2131034223;
			
			// aapt resource value: 0x7f05007a
			public const int olivedrab = 2131034234;
			
			// aapt resource value: 0x7f050023
			public const int orange = 2131034147;
			
			// aapt resource value: 0x7f050029
			public const int orangered = 2131034153;
			
			// aapt resource value: 0x7f050049
			public const int orchid = 2131034185;
			
			// aapt resource value: 0x7f05003e
			public const int palegoldenrod = 2131034174;
			
			// aapt resource value: 0x7f050062
			public const int palegreen = 2131034210;
			
			// aapt resource value: 0x7f05005a
			public const int paleturquoise = 2131034202;
			
			// aapt resource value: 0x7f050047
			public const int palevioletred = 2131034183;
			
			// aapt resource value: 0x7f050019
			public const int papayawhip = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int peachpuff = 2131034143;
			
			// aapt resource value: 0x7f05004f
			public const int peru = 2131034191;
			
			// aapt resource value: 0x7f050021
			public const int pink = 2131034145;
			
			// aapt resource value: 0x7f05000a
			public const int plugin_camera_black = 2131034122;
			
			// aapt resource value: 0x7f050044
			public const int plum = 2131034180;
			
			// aapt resource value: 0x7f050058
			public const int powderblue = 2131034200;
			
			// aapt resource value: 0x7f050070
			public const int purple = 2131034224;
			
			// aapt resource value: 0x7f05002d
			public const int red = 2131034157;
			
			// aapt resource value: 0x7f050054
			public const int rosybrown = 2131034196;
			
			// aapt resource value: 0x7f050086
			public const int royalblue = 2131034246;
			
			// aapt resource value: 0x7f050067
			public const int saddlebrown = 2131034215;
			
			// aapt resource value: 0x7f050032
			public const int salmon = 2131034162;
			
			// aapt resource value: 0x7f050038
			public const int sandybrown = 2131034168;
			
			// aapt resource value: 0x7f050017
			public const int seaShell = 2131034135;
			
			// aapt resource value: 0x7f05008c
			public const int seagreen = 2131034252;
			
			// aapt resource value: 0x7f050060
			public const int sienna = 2131034208;
			
			// aapt resource value: 0x7f050052
			public const int silver = 2131034194;
			
			// aapt resource value: 0x7f05006c
			public const int skyblue = 2131034220;
			
			// aapt resource value: 0x7f05007b
			public const int slateblue = 2131034235;
			
			// aapt resource value: 0x7f050078
			public const int slategray = 2131034232;
			
			// aapt resource value: 0x7f050079
			public const int slategrey = 2131034233;
			
			// aapt resource value: 0x7f050013
			public const int snow = 2131034131;
			
			// aapt resource value: 0x7f050093
			public const int springgreen = 2131034259;
			
			// aapt resource value: 0x7f050085
			public const int steelblue = 2131034245;
			
			// aapt resource value: 0x7f05000d
			public const int style_divider_color = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int style_red = 2131034124;
			
			// aapt resource value: 0x7f05004d
			public const int tan = 2131034189;
			
			// aapt resource value: 0x7f050099
			public const int teal = 2131034265;
			
			// aapt resource value: 0x7f05004a
			public const int thistle = 2131034186;
			
			// aapt resource value: 0x7f050000
			public const int time_line_color = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int title_button_color_gray = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int title_color = 2131034114;
			
			// aapt resource value: 0x7f0500a4
			public const int title_text_color = 2131034276;
			
			// aapt resource value: 0x7f050028
			public const int tomato = 2131034152;
			
			// aapt resource value: 0x7f0500a0
			public const int transparent = 2131034272;
			
			// aapt resource value: 0x7f0500a1
			public const int transparent2 = 2131034273;
			
			// aapt resource value: 0x7f050087
			public const int turquoise = 2131034247;
			
			// aapt resource value: 0x7f05003f
			public const int violet = 2131034175;
			
			// aapt resource value: 0x7f050037
			public const int wheat = 2131034167;
			
			// aapt resource value: 0x7f05000f
			public const int white = 2131034127;
			
			// aapt resource value: 0x7f050035
			public const int whitesmoke = 2131034165;
			
			// aapt resource value: 0x7f050012
			public const int yellow = 2131034130;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000d
			public const int activity_horizontal_margin = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int activity_vertical_margin = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int displayBigtext = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int displayMiddletext = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int displaySmalltext = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int displaySpecialtext = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int displaySuperSmalltext = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int displaySupertext = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int input = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int lefttext = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int navigation_title = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ordinary_button = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int ui_10_dip = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int view_Return = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int view_title = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_bar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bottom_bar_font_selelctor = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bottom_bar_icon_five_selelctor = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bottom_bar_icon_four_selelctor = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bottom_bar_icon_one_selelctor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bottom_bar_icon_three_selelctor = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bottom_bar_icon_tow_selelctor = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dingdan = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dingdanon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int edtbackground = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int faxian = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int faxianon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int gerenzhongxin = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int gerenzhongxinon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_splash_logo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int plugin_lc_smallicon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rh = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int xiaoxi = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int xiaoxiguanli = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int xiaoxion = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int BarTitle = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int LoadMainContent = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int MainContent = 2131230734;
			
			// aapt resource value: 0x7f080005
			public const int btnReturn = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int btnRight = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int btn_item_one = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int btn_item_three = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int btn_item_two = 2131230721;
			
			// aapt resource value: 0x7f080010
			public const int details = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int fragmentcontent = 2131230735;
			
			// aapt resource value: 0x7f080006
			public const int imgReturn = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int imgRight = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int ll_bottom_bar = 2131230737;
			
			// aapt resource value: 0x7f080003
			public const int rlTitle = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int txtReturn = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int txtRight = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int webView = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int webViewContainer = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonBarVw = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatMainVw = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CommonActivityVw = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CommonFragmentVw = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeMainVw = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoadMainVw = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainVw = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OrderMainVw = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int UserMainVw = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int album = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int camera_cancel = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int finish = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int invalidSD = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int no_photo = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int only_choose_num = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int photo = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int preview = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int strPoint = 2130968578;
			
			// aapt resource value: 0x7f04000c
			public const int timeprompt = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int unfinished = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int AppSplash = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int AppTheme = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int EdtDetailsNumberStyle = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int EdtDetailsStyle = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int Leparationline = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int LinearStyle = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int btn_input_amount_style = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int chat_content_date_style = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int chat_text_date_style = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int chat_text_name_style = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int layout_input_amount_style = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int txtDetailsStyle = 2131165191;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
