#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HybridApp.Resource", IsApplication=true)]

namespace HybridApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0400a2
			public const int PageBackground = 2130968738;
			
			// aapt resource value: 0x7f0400a3
			public const int TitleBackground = 2130968739;
			
			// aapt resource value: 0x7f04000b
			public const int albumback = 2130968587;
			
			// aapt resource value: 0x7f04003b
			public const int aliceblue = 2130968635;
			
			// aapt resource value: 0x7f040031
			public const int antiquewhite = 2130968625;
			
			// aapt resource value: 0x7f040091
			public const int aqua = 2130968721;
			
			// aapt resource value: 0x7f040072
			public const int aquamarine = 2130968690;
			
			// aapt resource value: 0x7f040039
			public const int azure = 2130968633;
			
			// aapt resource value: 0x7f040007
			public const int background = 2130968583;
			
			// aapt resource value: 0x7f040036
			public const int beige = 2130968630;
			
			// aapt resource value: 0x7f04001c
			public const int bisque = 2130968604;
			
			// aapt resource value: 0x7f04000e
			public const int black = 2130968590;
			
			// aapt resource value: 0x7f04001a
			public const int blanchedalmond = 2130968602;
			
			// aapt resource value: 0x7f04009c
			public const int blue = 2130968732;
			
			// aapt resource value: 0x7f04006a
			public const int blueviolet = 2130968682;
			
			// aapt resource value: 0x7f040001
			public const int bottom_item_line_color = 2130968577;
			
			// aapt resource value: 0x7f04005f
			public const int brown = 2130968671;
			
			// aapt resource value: 0x7f040043
			public const int burlywood = 2130968643;
			
			// aapt resource value: 0x7f0400a5
			public const int c1 = 2130968741;
			
			// aapt resource value: 0x7f0400a7
			public const int c10 = 2130968743;
			
			// aapt resource value: 0x7f0400a6
			public const int c4 = 2130968742;
			
			// aapt resource value: 0x7f040080
			public const int cadetblue = 2130968704;
			
			// aapt resource value: 0x7f040073
			public const int chartreuse = 2130968691;
			
			// aapt resource value: 0x7f04004e
			public const int chocolate = 2130968654;
			
			// aapt resource value: 0x7f040026
			public const int coral = 2130968614;
			
			// aapt resource value: 0x7f04007f
			public const int cornflowerblue = 2130968703;
			
			// aapt resource value: 0x7f040016
			public const int cornsilk = 2130968598;
			
			// aapt resource value: 0x7f040046
			public const int crimson = 2130968646;
			
			// aapt resource value: 0x7f040092
			public const int cyan = 2130968722;
			
			// aapt resource value: 0x7f04009e
			public const int darkblue = 2130968734;
			
			// aapt resource value: 0x7f040098
			public const int darkcyan = 2130968728;
			
			// aapt resource value: 0x7f040056
			public const int darkgoldenrod = 2130968662;
			
			// aapt resource value: 0x7f04005d
			public const int darkgray = 2130968669;
			
			// aapt resource value: 0x7f04009b
			public const int darkgreen = 2130968731;
			
			// aapt resource value: 0x7f04005e
			public const int darkgrey = 2130968670;
			
			// aapt resource value: 0x7f040053
			public const int darkkhaki = 2130968659;
			
			// aapt resource value: 0x7f040068
			public const int darkmagenta = 2130968680;
			
			// aapt resource value: 0x7f040081
			public const int darkolivegreen = 2130968705;
			
			// aapt resource value: 0x7f040025
			public const int darkorange = 2130968613;
			
			// aapt resource value: 0x7f040061
			public const int darkorchid = 2130968673;
			
			// aapt resource value: 0x7f040069
			public const int darkred = 2130968681;
			
			// aapt resource value: 0x7f040040
			public const int darksalmon = 2130968640;
			
			// aapt resource value: 0x7f040066
			public const int darkseagreen = 2130968678;
			
			// aapt resource value: 0x7f040084
			public const int darkslateblue = 2130968708;
			
			// aapt resource value: 0x7f04008a
			public const int darkslategray = 2130968714;
			
			// aapt resource value: 0x7f04008b
			public const int darkslategrey = 2130968715;
			
			// aapt resource value: 0x7f040096
			public const int darkturquoise = 2130968726;
			
			// aapt resource value: 0x7f040063
			public const int darkviolet = 2130968675;
			
			// aapt resource value: 0x7f04002a
			public const int deeppink = 2130968618;
			
			// aapt resource value: 0x7f040097
			public const int deepskyblue = 2130968727;
			
			// aapt resource value: 0x7f04007c
			public const int dimgray = 2130968700;
			
			// aapt resource value: 0x7f04007d
			public const int dimgrey = 2130968701;
			
			// aapt resource value: 0x7f04008f
			public const int dodgerblue = 2130968719;
			
			// aapt resource value: 0x7f040006
			public const int edt_font_value__color = 2130968582;
			
			// aapt resource value: 0x7f040057
			public const int firebrick = 2130968663;
			
			// aapt resource value: 0x7f040014
			public const int floralwhite = 2130968596;
			
			// aapt resource value: 0x7f040004
			public const int font_main_color = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int font_value_main_color = 2130968581;
			
			// aapt resource value: 0x7f04008d
			public const int forestgreen = 2130968717;
			
			// aapt resource value: 0x7f04002b
			public const int fuchsia = 2130968619;
			
			// aapt resource value: 0x7f040045
			public const int gainsboro = 2130968645;
			
			// aapt resource value: 0x7f040033
			public const int ghostwhite = 2130968627;
			
			// aapt resource value: 0x7f040020
			public const int gold = 2130968608;
			
			// aapt resource value: 0x7f040048
			public const int goldenrod = 2130968648;
			
			// aapt resource value: 0x7f04006d
			public const int gray = 2130968685;
			
			// aapt resource value: 0x7f04009a
			public const int green = 2130968730;
			
			// aapt resource value: 0x7f04005b
			public const int greenyellow = 2130968667;
			
			// aapt resource value: 0x7f04006e
			public const int grey = 2130968686;
			
			// aapt resource value: 0x7f04003a
			public const int honeydew = 2130968634;
			
			// aapt resource value: 0x7f040027
			public const int hotpink = 2130968615;
			
			// aapt resource value: 0x7f040050
			public const int indianred = 2130968656;
			
			// aapt resource value: 0x7f040082
			public const int indigo = 2130968706;
			
			// aapt resource value: 0x7f040010
			public const int ivory = 2130968592;
			
			// aapt resource value: 0x7f04003c
			public const int khaki = 2130968636;
			
			// aapt resource value: 0x7f040041
			public const int lavender = 2130968641;
			
			// aapt resource value: 0x7f040018
			public const int lavenderblush = 2130968600;
			
			// aapt resource value: 0x7f040074
			public const int lawngreen = 2130968692;
			
			// aapt resource value: 0x7f040015
			public const int lemonchiffon = 2130968597;
			
			// aapt resource value: 0x7f04005c
			public const int lightblue = 2130968668;
			
			// aapt resource value: 0x7f04003d
			public const int lightcoral = 2130968637;
			
			// aapt resource value: 0x7f040042
			public const int lightcyan = 2130968642;
			
			// aapt resource value: 0x7f04002f
			public const int lightgoldenrodyellow = 2130968623;
			
			// aapt resource value: 0x7f04004b
			public const int lightgray = 2130968651;
			
			// aapt resource value: 0x7f040065
			public const int lightgreen = 2130968677;
			
			// aapt resource value: 0x7f04004c
			public const int lightgrey = 2130968652;
			
			// aapt resource value: 0x7f040022
			public const int lightpink = 2130968610;
			
			// aapt resource value: 0x7f040024
			public const int lightsalmon = 2130968612;
			
			// aapt resource value: 0x7f04008e
			public const int lightseagreen = 2130968718;
			
			// aapt resource value: 0x7f04006b
			public const int lightskyblue = 2130968683;
			
			// aapt resource value: 0x7f040076
			public const int lightslategray = 2130968694;
			
			// aapt resource value: 0x7f040077
			public const int lightslategrey = 2130968695;
			
			// aapt resource value: 0x7f040059
			public const int lightsteelblue = 2130968665;
			
			// aapt resource value: 0x7f040011
			public const int lightyellow = 2130968593;
			
			// aapt resource value: 0x7f040094
			public const int lime = 2130968724;
			
			// aapt resource value: 0x7f040089
			public const int limegreen = 2130968713;
			
			// aapt resource value: 0x7f040030
			public const int linen = 2130968624;
			
			// aapt resource value: 0x7f04002c
			public const int magenta = 2130968620;
			
			// aapt resource value: 0x7f040071
			public const int maroon = 2130968689;
			
			// aapt resource value: 0x7f04007e
			public const int mediumaquamarine = 2130968702;
			
			// aapt resource value: 0x7f04009d
			public const int mediumblue = 2130968733;
			
			// aapt resource value: 0x7f040055
			public const int mediumorchid = 2130968661;
			
			// aapt resource value: 0x7f040064
			public const int mediumpurple = 2130968676;
			
			// aapt resource value: 0x7f040088
			public const int mediumseagreen = 2130968712;
			
			// aapt resource value: 0x7f040075
			public const int mediumslateblue = 2130968693;
			
			// aapt resource value: 0x7f040095
			public const int mediumspringgreen = 2130968725;
			
			// aapt resource value: 0x7f040083
			public const int mediumturquoise = 2130968707;
			
			// aapt resource value: 0x7f040051
			public const int mediumvioletred = 2130968657;
			
			// aapt resource value: 0x7f040090
			public const int midnightblue = 2130968720;
			
			// aapt resource value: 0x7f040034
			public const int mintcream = 2130968628;
			
			// aapt resource value: 0x7f04001b
			public const int mistyrose = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int moccasin = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int navajowhite = 2130968606;
			
			// aapt resource value: 0x7f040008
			public const int navigation_color = 2130968584;
			
			// aapt resource value: 0x7f04009f
			public const int navy = 2130968735;
			
			// aapt resource value: 0x7f040009
			public const int none_color = 2130968585;
			
			// aapt resource value: 0x7f04002e
			public const int oldlace = 2130968622;
			
			// aapt resource value: 0x7f04006f
			public const int olive = 2130968687;
			
			// aapt resource value: 0x7f04007a
			public const int olivedrab = 2130968698;
			
			// aapt resource value: 0x7f040023
			public const int orange = 2130968611;
			
			// aapt resource value: 0x7f040029
			public const int orangered = 2130968617;
			
			// aapt resource value: 0x7f040049
			public const int orchid = 2130968649;
			
			// aapt resource value: 0x7f04003e
			public const int palegoldenrod = 2130968638;
			
			// aapt resource value: 0x7f040062
			public const int palegreen = 2130968674;
			
			// aapt resource value: 0x7f04005a
			public const int paleturquoise = 2130968666;
			
			// aapt resource value: 0x7f040047
			public const int palevioletred = 2130968647;
			
			// aapt resource value: 0x7f040019
			public const int papayawhip = 2130968601;
			
			// aapt resource value: 0x7f04001f
			public const int peachpuff = 2130968607;
			
			// aapt resource value: 0x7f04004f
			public const int peru = 2130968655;
			
			// aapt resource value: 0x7f040021
			public const int pink = 2130968609;
			
			// aapt resource value: 0x7f04000a
			public const int plugin_camera_black = 2130968586;
			
			// aapt resource value: 0x7f040044
			public const int plum = 2130968644;
			
			// aapt resource value: 0x7f040058
			public const int powderblue = 2130968664;
			
			// aapt resource value: 0x7f040070
			public const int purple = 2130968688;
			
			// aapt resource value: 0x7f04002d
			public const int red = 2130968621;
			
			// aapt resource value: 0x7f040054
			public const int rosybrown = 2130968660;
			
			// aapt resource value: 0x7f040086
			public const int royalblue = 2130968710;
			
			// aapt resource value: 0x7f040067
			public const int saddlebrown = 2130968679;
			
			// aapt resource value: 0x7f040032
			public const int salmon = 2130968626;
			
			// aapt resource value: 0x7f040038
			public const int sandybrown = 2130968632;
			
			// aapt resource value: 0x7f040017
			public const int seaShell = 2130968599;
			
			// aapt resource value: 0x7f04008c
			public const int seagreen = 2130968716;
			
			// aapt resource value: 0x7f040060
			public const int sienna = 2130968672;
			
			// aapt resource value: 0x7f040052
			public const int silver = 2130968658;
			
			// aapt resource value: 0x7f04006c
			public const int skyblue = 2130968684;
			
			// aapt resource value: 0x7f04007b
			public const int slateblue = 2130968699;
			
			// aapt resource value: 0x7f040078
			public const int slategray = 2130968696;
			
			// aapt resource value: 0x7f040079
			public const int slategrey = 2130968697;
			
			// aapt resource value: 0x7f040013
			public const int snow = 2130968595;
			
			// aapt resource value: 0x7f040093
			public const int springgreen = 2130968723;
			
			// aapt resource value: 0x7f040085
			public const int steelblue = 2130968709;
			
			// aapt resource value: 0x7f04000d
			public const int style_divider_color = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int style_red = 2130968588;
			
			// aapt resource value: 0x7f04004d
			public const int tan = 2130968653;
			
			// aapt resource value: 0x7f040099
			public const int teal = 2130968729;
			
			// aapt resource value: 0x7f04004a
			public const int thistle = 2130968650;
			
			// aapt resource value: 0x7f040000
			public const int time_line_color = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int title_button_color_gray = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int title_color = 2130968578;
			
			// aapt resource value: 0x7f0400a4
			public const int title_text_color = 2130968740;
			
			// aapt resource value: 0x7f040028
			public const int tomato = 2130968616;
			
			// aapt resource value: 0x7f0400a0
			public const int transparent = 2130968736;
			
			// aapt resource value: 0x7f0400a1
			public const int transparent2 = 2130968737;
			
			// aapt resource value: 0x7f040087
			public const int turquoise = 2130968711;
			
			// aapt resource value: 0x7f04003f
			public const int violet = 2130968639;
			
			// aapt resource value: 0x7f040037
			public const int wheat = 2130968631;
			
			// aapt resource value: 0x7f04000f
			public const int white = 2130968591;
			
			// aapt resource value: 0x7f040035
			public const int whitesmoke = 2130968629;
			
			// aapt resource value: 0x7f040012
			public const int yellow = 2130968594;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f05000d
			public const int activity_horizontal_margin = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int activity_vertical_margin = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int displayBigtext = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int displayMiddletext = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int displaySmalltext = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int displaySpecialtext = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int displaySuperSmalltext = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int displaySupertext = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int input = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int lefttext = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int navigation_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ordinary_button = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int ui_10_dip = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int view_Return = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int view_title = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_bar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bottom_bar_font_selelctor = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bottom_bar_icon_five_selelctor = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bottom_bar_icon_four_selelctor = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bottom_bar_icon_one_selelctor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bottom_bar_icon_three_selelctor = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bottom_bar_icon_tow_selelctor = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dingdan = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dingdanon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int edtbackground = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int faxian = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int faxianon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int gerenzhongxin = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int gerenzhongxinon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_splash_logo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rh = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int xiaoxi = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int xiaoxiguanli = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int xiaoxion = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int BarTitle = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int LoadMainContent = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int MainContent = 2131230734;
			
			// aapt resource value: 0x7f080005
			public const int btnReturn = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int btnRight = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int btn_item_one = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int btn_item_three = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int btn_item_two = 2131230721;
			
			// aapt resource value: 0x7f080010
			public const int details = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int fragmentcontent = 2131230735;
			
			// aapt resource value: 0x7f080006
			public const int imgReturn = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int imgRight = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int ll_bottom_bar = 2131230737;
			
			// aapt resource value: 0x7f080003
			public const int rlTitle = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int txtReturn = 2131230727;
			
			// aapt resource value: 0x7f08000b
			public const int txtRight = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int webView = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int webViewContainer = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonBarVw = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatMainVw = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CommonActivityVw = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CommonFragmentVw = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeMainVw = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoadMainVw = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainVw = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OrderMainVw = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int UserMainVw = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int album = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int camera_cancel = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int finish = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int invalidSD = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int no_photo = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int only_choose_num = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int photo = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int preview = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int strPoint = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int timeprompt = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int unfinished = 2131099657;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int AppSplash = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int AppTheme = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int EdtDetailsNumberStyle = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int EdtDetailsStyle = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int Leparationline = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int LinearStyle = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int btn_input_amount_style = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int chat_content_date_style = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int chat_text_date_style = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int chat_text_name_style = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int layout_input_amount_style = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int txtDetailsStyle = 2131165191;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
